version: '3'

services:
  nginxproxy:
    depends_on:
      - nginx
      - db
      - wordpress
    image: nginx:latest
    container_name: proxy
    ports:
      - '80:80'
    restart: always
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'

  nginx:
    image: nginx:latest
    restart: always
    container_name: myweb
    volumes:
      - './myweb:/usr/share/nginx/html'

  flask:
    build: ./flask_docker
    restart: always
    container_name: myflask
    command: gunicorn -w 1 -b 0.0.0.0:80 wsgi:server # w = worker 프로세스 갯수 b = IP:PORT

  db:
    image: mysql:5.7
    restart: always
    container_name: mysqldb
    volumes:
      - 'mydb:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  wordpress:
    depends_on:
      - db
    container_name: wp
    build:
      context: './wp'
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

# 경로가 아닌 이름으로 볼륨 연결시 여기에 연결해줘야 함
volumes:
  mydb: #

